<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite [
        <!ELEMENT suite (test)*>
        <!ATTLIST suite
                name CDATA #REQUIRED>
        <!ELEMENT test (classes)*>
        <!ATTLIST test
                verbose CDATA #REQUIRED
                preserve-order CDATA #REQUIRED
                name CDATA #REQUIRED>
        <!ELEMENT classes (class)*>
        <!ELEMENT class (methods)*>
        <!ATTLIST class
                name CDATA #REQUIRED>
        <!ELEMENT methods (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ATTLIST include
                name CDATA #REQUIRED>
        ]>
<suite name="All Test Suite">
    <test verbose="2" preserve-order="true" name="C:/Users/IZIBILI GODWIN/Documents/Prightle/projects/Testify/move/Selenium_Webdriver_Automation/Page_Object_Model/Konga_POM">
        <classes>
            <class name="HomePageTest.LoginTests">
                <methods>
                    <include name="testACompanyLogo"/>
                    <include name="testAPageTitle"/>
                    <include name="CheckURL"/>
                    <include name="Login"/>
                </methods>
            </class>
            <class name="HomePageTest.DashboardTests">
                <methods><include name="AssertURL"/>
                    <include name="assertName"/>
                </methods>
            </class>
            <class name="HomePageTest.CategoryTest">
                <methods>
                    <include name="checkCurrentURL"/>
                    <include name="CategoryTest2"/>
                    <include name="CategoryTest3"/>
                    <include name="CategoryTest4"/>
                    <include name="CategoryTest5"/>
                    <include name="CheckingLogout"/>
                </methods>
            </class>

        </classes>
    </test>
</suite>